### ISSUE TITLE
Broken link in README.md

### ISSUE THREAD

**Issue by nirgal** [lukechilds/onionoo-node-client#55]
Link to Onionoo API docs looks broken.
https://onionoo.torproject.org/protocol.html#methods returns 404

**Comment by lukechilds** [comment]
Thanks, looks like they've changed the URL to:

https://metrics.torproject.org/onionoo.html#parameters

**Comment by lukechilds** [comment]
Oh and the file path

**Comment by lukechilds** [comment]
Fixed in https://github.com/lukechilds/onionoo-node-client/commit/02f304672451feecdf01cefaa1b2421c6e44a4a3

**Comment by dasanichris** [comment]
Hey Luke I was wondering if you could help me out. My phone and tablet have been hacked into anyway of trying to figure out who ? My daughters mom and I separated over summer now back together but I have this strong feeling it has to be a guy she knows there we're a bunch of little clues that lead me to think this.wondering if you could help me out I suck at this

________________________________________

**Comment by lukechilds** [comment]
@dasanichris lol I'm intrigued, are you a robot or is this actually a genuine request?

**Comment by dasanichris** [comment]
Lol this is a actual request ...looks like u are Good at this shot lol me not a clue figured I'd see if u could help haha kinda interesting request right hah

**Comment by lukechilds** [comment]
Haha wow. Ok, this is really not the place for this.

I'm not sure if you're aware since I noticed you're responding by email and you're watching this project on GitHub. But every time you respond to this email thread you're creating a new post on a GitHub issue for one of my projects:

[github.com/lukechilds/onionoo-node-client/issues/55](https://github.com/lukechilds/onionoo-node-client/issues/55)

I use GitHub issues to track bugs in my projects, and poor @nirgal will be getting spammed with notifications.

My email address is listed on my GitHub profile for people who want to contact me privately.

In answer to your question if I can help you. If you are implying you think your partner was involved, I would recommend you raise these concerns with her, not some random dude on the internet. If you just want to ensure your devices are secure, I would recommend you factory reset them.

Please don't respond to this thread anymore, good luck getting your problem resolved.
